---
language: python
python: "2.7"

sudo: required

# Use the docker for testing
services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - sshpass

install:
  - which ssh-keygen
  - which ssh-agent
  - which ssh-add

  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Install python module and role dependencies
  - test -f requirements.txt && pip install -r requirements.txt
  - test -f requirements.yml && ansible-galaxy install -p tests/roles -r requirements.yml
  - test -f requirements-test.yml && ansible-galaxy install -p tests/roles -r requirements-test.yml

  # Start a sshd container for testing at localhost:4848, enable root login, password is 123456
  - docker pull danielguerra/alpine-sshd
  - docker rm alpine-sshd || true
  - docker run -p 4848:22 --name alpine-sshd --hostname alpine-sshd -d danielguerra/alpine-sshd sh -c 'echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && exec /usr/sbin/sshd -D'
  - ssh-keygen -f "~/.ssh/known_hosts" -R [localhost]:4848 || true
  - echo -e "123456\n123456" | docker exec -i alpine-sshd passwd

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\n' >ansible.cfg

  # Create ssh askpass shell
  - printf '#!/bin/sh\necho 123456\n' >ps.sh
  - chmod +x ps.sh

script:
  - set -e

  # Basic role syntax check
  - echo ========== [syntax check] ==========
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  - echo ========== [run 1st round, no key] ==========
  - true && ! ansible-playbook tests/test.yml -i tests/inventory
  - true && ! ansible-playbook tests/test.yml -i tests/inventory-pass

  - echo ========== [run 2nd round, with a uncrypted key pair] ==========
  - ssh -O exit -o Port=4848 -o User=root -o ControlPath=/home/travis/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 || true
  - ssh-keygen -N '' -f ~/.ssh/id_rsa
  - true && ! ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory-pass
  - ansible-playbook tests/test.yml -i tests/inventory

  - echo ========== [run 3rd round, with a uncrypted private key] ==========
  - ssh -O exit -o Port=4848 -o User=root -o ControlPath=/home/travis/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 || true
  - rm ~/.ssh/id_rsa ~/.ssh/id_rsa.pub && ssh-keygen -N '' -f ~/.ssh/id_rsa && rm ~/.ssh/id_rsa.pub
  - true && ! ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory-pass
  - ansible-playbook tests/test.yml -i tests/inventory

  - echo ========== [run 4th round, install keys via control persist path] ==========
  - rm ~/.ssh/id_rsa && ssh-keygen -N '' -f ~/.ssh/id_rsa
  - ansible-playbook tests/test.yml -i tests/inventory

  - echo ========== [run 5th round, with a crypted key pair] ==========
  - ssh -O exit -o Port=4848 -o User=root -o ControlPath=/home/travis/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 || true
  - docker exec -i alpine-sshd sh -c 'rm ~/.ssh -rf' && ssh-keygen -p -P '' -N '123456' -f ~/.ssh/id_rsa
  - true && ! ansible-playbook tests/test.yml -i tests/inventory
  - true && ! ansible-playbook tests/test.yml -i tests/inventory-pass

  - echo ========== [run 6th round, with a crypted key pair in ssh-agent] ==========
  - eval `ssh-agent`
  - echo | DISPLAY=:0 SSH_ASKPASS="$PWD/ps.sh" ssh-add
  - ansible-playbook tests/test.yml -i tests/inventory

  - echo ========== [run 7th round, with --become] ==========
  - ssh -O exit -o Port=4848 -o User=root -o ControlPath=/home/travis/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 || true
  - docker exec -i alpine-sshd sh -c 'rm ~/.ssh -rf'
  - eval `ssh-agent`
  - echo | DISPLAY=:0 SSH_ASKPASS="$PWD/ps.sh" ssh-add
  - ansible-playbook tests/test.yml -i tests/inventory-pass --become
  - test "$(docker exec alpine-sshd sh -c 'cat $HOME/.ssh/authorized_keys' | cut -d ' ' -f 1,2 | uniq | md5sum)" = "$(cat ~/.ssh/id_rsa.pub | cut -d ' ' -f 1,2 | md5sum)"

  - echo ========== [run 8th round, shell type is fish] ==========
  - ssh -O exit -o Port=4848 -o User=root -o ControlPath=/home/travis/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 || true
  - docker exec -i alpine-sshd sh -c 'rm ~/.ssh -rf'
  - docker exec -i alpine-sshd sh -c 'apk update && apk add fish'
  - ansible-playbook tests/test.yml -i tests/inventory-pass --become -e ansible_shell_executable=/usr/bin/fish -e ansible_shell_type=fish -vvvvv
  - test "$(docker exec alpine-sshd sh -c 'cat $HOME/.ssh/authorized_keys' | cut -d ' ' -f 1,2 | uniq | md5sum)" = "$(cat ~/.ssh/id_rsa.pub | cut -d ' ' -f 1,2 | md5sum)"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
