---
language: python
python: "2.7"

sudo: required

# Use the docker for testing
services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - sshpass

install:
  - which ssh-keygen
  - which ssh-agent
  - which ssh-add

  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Install python module and role dependencies
  - test -f requirements.txt && pip install -r requirements.txt
  - test -f requirements.yml && ansible-galaxy install -p tests/roles -r requirements.yml
  - test -f requirements-test.yml && ansible-galaxy install -p tests/roles -r requirements-test.yml

  # Start a sshd container for testing at localhost:4848, enable root login, password is 123456
  - docker pull danielguerra/alpine-sshd
  - docker rm alpine-sshd || true
  - docker run -p 4848:22 --name alpine-sshd --hostname alpine-sshd -d danielguerra/alpine-sshd sh -c 'echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && exec /usr/sbin/sshd -D'
  - ssh-keygen -f "~/.ssh/known_hosts" -R [localhost]:4848 || true
  - echo -e "123456\n123456" | docker exec -i alpine-sshd passwd

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\n' >ansible.cfg

  # Create ssh askpass shell
  - printf '#!/bin/sh\necho 123456\n' >ps.sh
  - chmod +x ps.sh

script:
  # Basic role syntax check
  - echo ========== [syntax check] ==========
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  - echo ========== [run 1st round, no key] ==========
  - ! ansible-playbook tests/test.yml -i tests/inventory
  - ! ansible-playbook tests/test.yml -i tests/inventory-pass

  - echo ========== [run 2nd round, with uncrypted keys] ==========
  - ssh-keygen -N '' -f ~/.ssh/id_rsa
  - ! ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory-pass
  - ansible-playbook tests/test.yml -i tests/inventory
  - rm ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
  - ssh-keygen -N '' -f ~/.ssh/id_dsa -t dsa
  - ansible-playbook tests/test.yml -i tests/inventory
  - docker exec -i alpine-sshd sh 'rm ~/.ssh -rf'

  - echo ========== [run 3rd round, with crypted keys] ==========
  - ssh-keygen -p -P '' -N '123456' -f ~/.ssh/id_dsa
  - ! ansible-playbook tests/test.yml -i tests/inventory
  - ! ansible-playbook tests/test.yml -i tests/inventory-pass
  - eval `ssh-agent` && DISPLAY=:0 SSH_ASKPASS="$PWD/ps.sh" ssh-add && ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
