---
- name: include ssh-copy-id tasks if needed
  when:
  - not ansible_pubkey_login_is_disabled
  - ([ hostvars[inventory_hostname].ansible_connection | d('smart') ]) | intersect(['ssh', 'smart', 'paramiko']) | list
  include_tasks: ssh-copy-id.yml
