---
- name: Include ssh-copy-id tasks if needed
  when:
  - not ansible_pubkey_login_is_disabled
  - (hostvars[inventory_hostname].ansible_connection | d('smart')) in ['ssh', 'smart', 'paramiko']
  ansible.builtin.include_tasks: ssh-copy-id.yml
